version: '3.7'

services:
  web:
    build: .
    container_name: wordpress_apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/datakiin/wp-gen/wp-gen/config/wp-gen.cnf:/root/.my.cnf
      - /home/datakiin/wp-gen/wp-gen:/wp-gen
      - /etc/hosts:/etc/hosts
      - /etc/wordpress:/etc/wordpress
      - /var/www:/var/www
      - /var/lib/projects:/var/lib/projects
      - /etc/apache2/sites-available:/etc/apache2/sites-available
      - /etc/wp-gen:/etc/wp-gen
    networks:
      - wp-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: Admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: html
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./html_database_dump.sql:/docker-entrypoint-initdb.d/html_database_dump.sql
      - ./create_user.sql:/docker-entrypoint-initdb.d/create_user.sql
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress_phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    networks:
      - wp-network

volumes:
  db_data:
    name: wpdb

networks:
  wp-network:
    driver: bridge
