version: '3.7'

services:
  web:
    build: .
    container_name: wordpress_apache
    ports:
      - "80:80"
      - "8443:443"
    volumes:
      - ./wp-gen:/home/wp-gen
    networks:
      - wp-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: wordpress_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress_phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    networks:
      - wp-network

volumes:
  db_data:

networks:
  wp-network:
    driver: bridge
