Alias /littleshop /littleshop.local/littleshop.local

<Directory /littleshop.local/littleshop.local>
    Options FollowSymLinks
    AllowOverride Limit Options FileInfo
    DirectoryIndex index.php
    Require all granted
</Directory>

# Error and Access Logs
ErrorLog /dev/stderr
CustomLog /dev/stderr combined
